language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arun23/docker-info -f Dockerfile.dev .

script:
  - docker run -e CI=true arun23/docker-info npm run test -- --coverage